version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:111222333444:task-definition/demo-flask-app-task:1"
        LoadBalancerInfo:
          ContainerName: "demo-flask-app-container"
          ContainerPort: 80